EA-2581: Include correct headers in responses
europeana/entity-management pull request #89
Opened 2021-06-17 15:38 UTC by ikattey

2021-06-23 18:41 UTC, gsergiu requested changes
There are still some configurations and header values to be fixed

2021-06-23 18:41 UTC, gsergiu commented on entity-management-web/src/integration-test/java/eu/europeana/entitymanagement/web/EMControllerIT.java
> +        checkAllowHeaderForGET(resultActions);
can we switch to checkAllowHeaderForDPGP?

2021-06-23 18:41 UTC, gsergiu commented on entity-management-web/src/integration-test/java/eu/europeana/entitymanagement/web/EMControllerIT.java
> +        checkAllowHeaderForGET(resultActions);
can we switch to checkAllowHeaderForDPGP?

2021-06-23 18:41 UTC, gsergiu commented on entity-management-web/src/integration-test/java/eu/europeana/entitymanagement/web/EMControllerIT.java
> +                is(CONTENT_TYPE_JSONLD_UTF8)))
can we add the checkAllowHeaderForDPGP?

2021-06-23 18:41 UTC, gsergiu commented on entity-management-web/src/integration-test/java/eu/europeana/entitymanagement/web/EMControllerIT.java
> +        checkAllowHeaderForGET(resultActions);
can we switch to checkAllowHeaderForDPGP?

2021-06-23 18:41 UTC, gsergiu commented on entity-management-web/src/integration-test/java/eu/europeana/entitymanagement/web/EMControllerIT.java
> +                .andExpect(header().stringValues(HttpHeaders.VARY, hasItems(containsString(HttpHeaders.ACCEPT))));
the delete method must not include a Vary header

2021-06-23 18:41 UTC, gsergiu commented on entity-management-web/src/integration-test/java/eu/europeana/entitymanagement/web/EMControllerIT.java
> +                        is(MediaType.APPLICATION_XML_VALUE)))
the response should include application/rdf+xml in content type response header

2021-06-23 18:41 UTC, gsergiu commented on entity-management-web/src/main/java/eu/europeana/entitymanagement/config/WebMvcConfig.java
> +                .allowedMethods("*")
we can either create the mappings for individual patterns (i.e. /entity/, /entity/*/*,  /entity/*/*/* ) or use the  @CrossOrigin annotation on individual methods

2021-06-23 18:41 UTC, gsergiu commented on entity-management-web/src/main/java/eu/europeana/entitymanagement/config/WebMvcConfig.java
> +                .exposedHeaders(HttpHeaders.ALLOW)
DELETE /entity/{type}/{identifier}/management does not return allow header, but it might be acceptable to include it in all responses

2021-06-23 18:41 UTC, gsergiu commented on entity-management-web/src/main/java/eu/europeana/entitymanagement/web/EMController.java
> +			String responseContentType = GET_XML_ACCEPT_HEADERS.contains(acceptHeader)
I think that we need to return always application/rdf+xml in content type header, even when the request comes with application/xml

2021-06-23 18:42 UTC, ikattey commented on entity-management-web/src/integration-test/java/eu/europeana/entitymanagement/web/EMControllerIT.java
> +        checkAllowHeaderForGET(resultActions);
@gsergiu why?

2021-06-23 18:44 UTC, ikattey commented on entity-management-web/src/main/java/eu/europeana/entitymanagement/config/WebMvcConfig.java
> +                .allowedMethods("*")
Not sure what you mean. This is how CORS is configured – the wildcard is just a shortcut for all HTTP methods.

2021-06-23 18:49 UTC, ikattey commented on entity-management-web/src/integration-test/java/eu/europeana/entitymanagement/web/EMControllerIT.java
> +        checkAllowHeaderForGET(resultActions);
See my response above.

2021-06-23 18:49 UTC, ikattey commented on entity-management-web/src/integration-test/java/eu/europeana/entitymanagement/web/EMControllerIT.java
> +                is(CONTENT_TYPE_JSONLD_UTF8)))
This is a valid point. I'll check for the Allow header here.

2021-06-24 07:35 UTC, gsergiu commented on entity-management-web/src/integration-test/java/eu/europeana/entitymanagement/web/EMControllerIT.java
> +        checkAllowHeaderForGET(resultActions);
You are right here, the issues is in the specs. Indeed for the .jsonld and .xml only the GET method exists .... We will need to update the specs

2021-06-30 20:38 UTC, merged